site_name: Portainer Documentation
nav:
    - Home: index.md
    - Portainer 1.24.1 : /v1.24.1/
    - Portainer CE 2.0 : /v2.0/
    - Portainer Business: /be/
theme:
  features:
    - instant
  logo: assets/logo.png
  name: material
  palette:
    primary: light-blue
repo_name: portainer/portainer
repo_url: https://github.com/portainer/portainer-docs
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/linkedin
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/youtube
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/facebook
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/reddit
      link: https://twitter.com/squidfunk