site_name: Documentation
nav:
    - Home: index.md
    - Portainer CE 2.0 Admin Guide:
      - Deploying Portainer:
        - 'Requirements' : 'v2.0/deploy/requirements.md'
        - 'CLI Options' : 'v2.0/deploy/cli.md'
        - 'Deploying on Linux' : 'v2.0/deploy/linux.md'
        - 'Deploying on Windows Server' : 'v2.0/deploy/windowsserver.md'
        - 'Deploying on Windows 10' : 'v2.0/deploy/windows10.md'
        - 'Using SSL with Portainer' : 'v2.0/deploy/ssl.md'
        - 'Initial Setup' : 'v2.0/deploy/initial.md'
      - Managing Endpoints:
        - 'Add Local Endpoint' : 'v2.0/endpoints/local.md'
        - 'Add Docker Endpoint' : 'v2.0/endpoints/docker.md'
        - 'Add Docker Swarm Endpoint' : 'v2.0/endpoints/swarm.md'
        - 'Add Kubernetes Endpoint' : 'v2.0/endpoints/kubernetes.md'
        - 'Add Edge Endpoint' : 'v2.0/endpoints/edge.md'
        - 'Add ACI Endpoint' : 'v2.0/endpoints/aci.md'
        - 'Creating Endpoints Groups and Endpoint Tags' : 'v2.0/endpoints/groupstags.md'
        - 'Managing Endpoints Access' : 'v2.0/endpoints/access.md'
        - 'Add Endpoint through Portainer API' : 'v2.0/endpoints/api.md'
      - Authentication Sources:
        - 'LDAP' : 'v2.0/auth/ldap.md'
        - 'OAuth' : 'v2.0/auth/oauth.md'
        - 'Internal' : 'v2.0/auth/internal.md'
      - Managing Users & Teams:
        - 'Create a User' : 'v2.0/users/create.md'
        - 'Create a Team' : 'v2.0/users/create-team.md'
        - 'Promote a User as Admin' : 'v2.0/users/promoting.md'
        - 'Add a User to a Team' : 'v2.0/users/user-team.md'
        - 'Reset User Password' : 'v2.0/users/reset-user.md'
        - 'Reset Administrator Password' : 'v2.0/users/reset-admin.md'
      - Registries:
        - 'Connect to a Registry' : 'v2.0/registries/connect.md'
        - 'Enable Docker Hub Authentication' : 'v2.0/registries/auth-docker-hub.md'
      - Configuring Settings:
        - 'Security Options' : 'v2.0/settings/security.md'
        - 'Edge Computing' : 'v2.0/settings/edge.md'
        - 'App Templates' : 'v2.0/settings/apps.md'
      - Advanced Deployments:
        - 'Using Portainer with Reverse Proxies':
            - 'Traefik' : 'v2.0/ad/traefik/rp-traefik.md'
            - 'Nginx' : 'v2.0/ad/nginx/rp-nginx.md'
      - FAQs : 'v2.0/troubleshooting/troubleshooting.md'
      - Deprecated and Removed Features : 'v2.0/troubleshooting/deprecated.md'
    - Portainer CE 2.0 User Guide (WIP):
      - Stacks:
        - 'Add/Create a Stack' : 'v2.0/stacks/create.md'
        - 'Create a template from a Stack' : 'v2.0/stacks/template.md'
        - 'Duplicate / Migrate Stacks' : 'v2.0/stacks/duplicate_migration.md'
        - 'Inspect a Stack' : 'v2.0/stacks/inspect.md'
      - Containers:
        - 'Create New Container' : 'v2.0/containers/create.md'
        - 'Delete/Remove a Container' : 'v2.0/containers/delete.md'
        - 'Inspect a Container' : 'v2.0/containers/inspect.md'
        - 'View logs' : 'v2.0/containers/logs.md'
        - 'View Container stats' : 'v2.0/containers/stats.md'
        - 'Access container console' : 'v2.0/containers/console.md'
        - 'Change Container Ownership' : 'v2.0/containers/ownership.md'
        - 'Duplicated/Edit a Container' : 'v2.0/containers/duplicate-edit.md'
      - App Templates:
        - 'Deploy an Stack' : 'v2.0/templates/deploy_stack.md'
        - 'Deploy an App (Container)' : 'v2.0/templates/deploy_container.md'
      - Services:
        - 'Create a New Service' : 'v2.0/services/create.md'
        - 'Scaling a Service' : 'v2.0/services/scale.md'
        - 'View Service Logs' : 'v2.0/services/logs.md'
        - 'Service Task Status' : 'v2.0/services/status.md'
        - 'Configure Service Options' : 'v2.0/services/options.md'
        - 'Rollback a Service' : 'v2.0/services/rollback.md'
      - Applications:
        - 'Create a New Application' : 'v2.0/apps/create.md'
      - Volumes:
        - 'Browse a Volume' : 'v2.0/volumes/browse.md'
        - 'Create a Volume' : 'v2.0/volumes/create.md'
        - 'Attach an Existing Volume' : 'v2.0/volumes/attaching.md'
    - FAQs : 'v2.0/troubleshooting/troubleshooting.md'
    - Videos : 'https://www.youtube.com/channel/UC7diMJcrULjDseq5yhSUZgg/videos'
    - Older Releases :
        - CE 1.23.2 :
            - 'Agent' : 'archive/1.23.2/agent.md'
            - 'API' : 'archive/1.23.2/API.md'
            - 'Configuration' : 'archive/1.23.2/configuration.md'
            - 'Deployment' : 'archive/1.23.2/deployment.md'
            - 'External Endpoints' : 'archive/1.23.2/external_endpoints.md'
            - 'Limitations' : 'archive/1.23.2/limitations.md'
            - 'Templates' : 'archive/1.23.2/templates.md'
            - 'Troubleshooting' : 'archive/1.23.2/troubleshooting.md'
            - 'User Guide' : 'archive/1.23.2/userguide.md'
            - 'FAQ' : 'archive/1.23.2/faq.md'    
extra_css:
    - css/extra.css
extra_javascript:
    - js/extrajs.js
theme:
  font:
    text: raleway
  features:
    - instant
  logo: assets/logo.png
  favicon: assets/icon.webp
  name: material
  palette:
    primary: light-blue
repo_name: portainer/portainer
repo_url: https://github.com/portainer/portainer-docs
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/portainerio
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/portainer/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC7diMJcrULjDseq5yhSUZgg
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/portainerio/
    - icon: fontawesome/brands/reddit
      link: https://reddit.com/r/portainer
