site_name: Portainer Documentation
nav:
    - Home: index.md
    - Portainer 1.24.1: '#'
    - Portainer CE 2.0:
      - Deploying Portainer:
        - 'Requirements' : 'v2.0/deploy/requirements.md'
        - 'CLI options' : 'v2.0/deploy/clioptions.md'
        - 'Deploying on Linux' : 'v2.0/deploy/linux.md'
        - 'Deploying on Windows Server' : 'v2.0/deploy/windowsserver.md'
        - 'Deploying on Windows 10' : 'v2.0/deploy/windows10.md'
        - 'Using SSL with Portainer' : 'v2.0/deploy/ssl.md'
        - 'Initial Setup' : 'v2.0/deploy/initialsetup.md'
      - Adding Endpoints:
        - 'Local Endpoint' : 'v2.0/endpoints/local.md'
        - 'Deploy and connect Portainer agent in Docker' : 'v2.0/endpoints/docker.md'
        - 'Deploy and connect Portainer agent in Swarm' : 'v2.0/endpoints/swarm.md'
        - 'Deploy and connect Portainer agent in Kubernetes' : 'v2.0/endpoints/kubernetes.md'
        - 'Kubernetes: Configuring Cluster Capabilities and Permissions' : 'v2.0/endpoints/kcandp.md'
        - 'Deploy and connect Portainer Edge agent' : 'v2.0/endpoints/edge.md'
        - 'Deploy and connect ACI endpoint' : 'v2.0/endpoints/aci.md'
        - 'Creating Endpoints Groups and Endpoint Tags' : 'v2.0/endpoints/groupstags.md'
        - 'Managing Endpoints Access' : 'v2.0/endpoints/access.md'
      - Authentication Sources:
        - 'LDAP' : 'v2.0/auth/ldap.md'
        - 'OAuth' : 'v2.0/auth/oauth.md'
        - 'Internal' : 'v2.0/auth/internal.md'
      - Managing users:
        - 'Create a User' : 'v2.0/users/create.md'
      - Managing Teams:
        - 'Create a Team' : 'v2.0/teams/create.md'
      - Registries:
        - 'Connect to a registry' : 'v2.0/registries/connect.md'
      - Configuring Settings:
        - 'Security Options' : 'v2.0/settings/security.md'
        - 'Edge Computing' : 'v2.0/settings/edge.md'
        - 'App Templates' : 'v2.0/settings/apps.md'
      - Advanced Deployments:
        - 'Using Portainer with Reverse Proxies' : 'v2.0/ad/rp.md'
      - Portainer Deployment Troubleshooting : 'v2.0/troubleshooting/index.md'
    - Portainer Business: '#'
theme:
  features:
    - instant
  logo: assets/logo.png
  name: material
  palette:
    primary: light-blue
repo_name: portainer/portainer
repo_url: https://github.com/portainer/portainer-docs
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/linkedin
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/youtube
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/facebook
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/reddit
      link: https://twitter.com/squidfunk
